# Generated by Django 2.2.14 on 2020-08-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200802_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('AR', 'Art')], default='CS', max_length=2),
        ),
    ]
