# Generated by Django 2.2.14 on 2020-08-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('CP', 'Coloured Pencils'), ('AC', 'Acrylics'), ('WT', 'Watercolours'), ('OP', 'Oil Paints'), ('DG', 'Digital')], default='CS', max_length=2),
        ),
    ]
